name: "Helm Chart Releaser 2"
description: "Host a Helm charts repo on GitHub Pages"
author: "The Helm authors & Web7"
branding:
  color: blue
  icon: anchor
inputs:
  version:
    description: "The chart-releaser version to use (default: v1.0.0)"
  charts_dir:
    description: The charts directory
    default: charts
  charts_repo_url:
    description: "The GitHub Pages URL to the charts repo (default: https://<owner>.github.io/<repo>)"
    required: true
  no_index:
    description: "Do not generate and do not upload index file to charts repo"
    required: false
  scan:
    description: "Scan charts directories recursively starts from charts directory"
    required: false
runs:
  using: "node12"
  main: "main.js"
